### PR TITLE
[Font Bakery Dashboard] create family: Bebas Neue

### PR DESCRIPTION
**Pull request by vv-monsalve**
[full report](https://fontbakery.graphicore.de/dispatcher/process/7d9b4410-8e89-4b97-a49c-ee55ebfdb964)

# Step # 0 Review the Request and Generate the Files Package

**finished: OK**

All tasks completed successfully.

### Task ApproveProcess OK

**@vv-monsalve** confirms the family package.

Report…

### Files
 * `BebasNeue-Regular.ttf` *61400 Bytes*
 * `DESCRIPTION.en_us.html` *362 Bytes*
 * `METADATA.pb` *440 Bytes*
 * `OFL.txt` *4337 Bytes*

[zip file download](/download/persistence/2ea681b39d0b5474dd6432fa203af63180c279cab2bbbf19ca14ee6d83a5dbc4:1/Bebas%20Neue.zip)

### Metadata
**commit** 686d14af640c17af3691c597778f121d840d9051  
**commitDate** 2019-10-07T22:21:38.000Z  
**sourceDetails** 

&emsp;**status** `"OK"`  
&emsp;**name** `"Bebas Neue"`  
&emsp;**keySuffix** `""`  
&emsp;**nameConfirmed** `""`  
&emsp;**upstream** `"https://github.com/dharmatype/Bebas-Neue"`  
&emsp;**branch** `""`  
&emsp;**fontfilesPrefix** `"fonts/BebasNeue(2018)ByDhamraType/ttf/BebasNeue-"`  
&emsp;**genre** `"Display"`  
&emsp;**designer** `"Ryoichi Tsunekawa"`  
**familyPath** fonts/BebasNeue(2018)ByDhamraType/ttf  
**repository** https://github.com/dharmatype/Bebas-Neue  
**branch** master  
**googleMasterDir** (unknown)  
**isUpdate** `false`  
**licenseDir** ofl

---

# Step # 1 Quality Assurance

**finished: OK**

All tasks completed successfully.

### Task Fontbakery OK

**@vv-monsalve** Font Bakery looks good.

Report…

## [Font Bakery Result](https://fontbakery.graphicore.de/report/a92e65df-01bf-4fa3-b4ae-4c32ed9c08eb)

| 💔 ERROR | 🔥 FAIL | ⚠ WARN | 💤 SKIP | 🛈 INFO | 🍞 PASS |
|:-----:|:----:|:----:|:----:|:----:|:----:|
| 0 | 0 | 4 | 32 | 8 | 116 |
| 0 % | 0 % | 2.5 % | 20 % | 5 % | 72.5 % |

*created* Mon Oct 14 2019 15:26:46 GMT+0000 (Coordinated Universal Time)<br />
*started* Mon Oct 14 2019 15:26:46 GMT+0000 (Coordinated Universal Time)<br />
*finished* Mon Oct 14 2019 15:26:51 GMT+0000 (Coordinated Universal Time)

### Task Diffenator OK

**@vv-monsalve** Diffenator is looking  good.

### Task BrowsersDiffsAndPreviews OK

**@vv-monsalve** Browsers diffs and previews are looking  good.

### CODE REVIEW

**Comment by graphicore** [comment]
Updated:

---
[full report](http://localhost:3000/dispatcher/process/67a55234-b188-44f7-8f5c-966556fd444f)

# Step # 0 Review the Request and Generate the Files Package

**finished: OK**

All tasks completed successfully.

### Task ApproveProcess OK

**@graphicore** confirms the family package.

Report…

## Files Package for *ABeeZee*
### Files
 * `ABeeZee-Italic.ttf` *47764 Bytes*
 * `ABeeZee-Regular.ttf` *46124 Bytes*
 * `DESCRIPTION.en_us.html` *345 Bytes*
 * `FONTLOG.txt` *1765 Bytes*
 * `METADATA.pb` *626 Bytes*
 * `OFL.txt` *4466 Bytes*


[zip file download](http://localhost:3000/download/persistence/a51770aeaf3d57a835da37f38b1dde3313ad4b6d747e49255385785782f2810e:6/ABeeZee.zip)


### Metadata
**commit** 1de10e9a33fbe586897d35f9da29ab95df1b6d37  
**commitDate** 2015-06-15T19:55:05.000Z  
**sourceDetails** 

&emsp;**status** `"OK"`  
&emsp;**name** `"ABeeZee"`  
&emsp;**keySuffix** `""`  
&emsp;**nameConfirmed** `"Passed"`  
&emsp;**upstream** `"https://github.com/googlefonts/abeezee.git"`  
&emsp;**branch** `""`  
&emsp;**fontfilesPrefix** `"fonts/ttf/ABeeZee-"`  
&emsp;**genre** `"Sans Serif"`  
&emsp;**designer** `""`  
**familyPath** fonts/ttf  
**repository** https://github.com/googlefonts/abeezee.git  
**branch** master  
**googleMasterDir** ofl/abeezee  
**isUpdate** `true`  
**licenseDir** ofl


---

# Step # 1 Quality Assurance

**finished: OK**

All tasks completed successfully.

### Task Fontbakery OK

**@graphicore** Font Bakery looks good.

Report…

## [Font Bakery Result](http://localhost:3000/report/b1325fd6-8276-4a40-9e33-410f59caabf2)

| 💔 ERROR | 🔥 FAIL | ⚠ WARN | 💤 SKIP | 🛈 INFO | 🍞 PASS |
|:-----:|:----:|:----:|:----:|:----:|:----:|
| 0 | 14 | 10 | 57 | 11 | 200 |
| 0 % | 4.79 % | 3.42 % | 19.52 % | 3.77 % | 68.49 % |

*created* Mon Oct 14 2019 16:00:47 GMT+0000 (Coordinated Universal Time)<br />
*started* Mon Oct 14 2019 16:00:48 GMT+0000 (Coordinated Universal Time)<br />
*finished* Mon Oct 14 2019 16:02:53 GMT+0000 (Coordinated Universal Time)

### Task Diffenator OK

**@graphicore** Diffenator is looking  good.

Report…

## Diffenator Result
### Preparation Logs
 * `Added file "before/ABeeZee-Italic.ttf".`
 * `Added file "before/ABeeZee-Regular.ttf".`
 * `Added file "after/ABeeZee-Italic.ttf".`
 * `Added file "after/ABeeZee-Regular.ttf".`
 * `Added file "after/DESCRIPTION.en_us.html".`
 * `Added file "after/FONTLOG.txt".`
 * `Added file "after/METADATA.pb".`
 * `Added file "after/OFL.txt".`

### Results
 * browse report: [**Italic**](http://localhost:3000/browse/persistence/65c17bbbd744d7432f9de1847fb0c24c3fb9532df8c48c76868b7675f7099ec9:2/report.html) or download: [zip file](http://localhost:3000/download/persistence/65c17bbbd744d7432f9de1847fb0c24c3fb9532df8c48c76868b7675f7099ec9:2/Diffenator_ABeeZee_Italic.zip)
 * browse report: [**Regular**](http://localhost:3000/browse/persistence/584e023197c812760bd3aac7b89b11953524e1c4c947f802140b698dd3a14a86:2/report.html) or download: [zip file](http://localhost:3000/download/persistence/584e023197c812760bd3aac7b89b11953524e1c4c947f802140b698dd3a14a86:2/Diffenator_ABeeZee_Regular.zip)

*started* Mon Oct 14 2019 20:23:26 GMT+0000 (Coordinated Universal Time)<br />
*finished* Mon Oct 14 2019 20:23:36 GMT+0000 (Coordinated Universal Time)

### Task BrowsersDiffsAndPreviews OK

**@graphicore** Browsers diffs and previews are looking  good.

Report…

## Browser diffs and previews Result
### Preparation Logs
 * `Added file "before/ABeeZee-Italic.ttf".`
 * `Added file "before/ABeeZee-Regular.ttf".`
 * `Added file "after/ABeeZee-Italic.ttf".`
 * `Added file "after/ABeeZee-Regular.ttf".`
 * `Added file "after/DESCRIPTION.en_us.html".`
 * `Added file "after/FONTLOG.txt".`
 * `Added file "after/METADATA.pb".`
 * `Added file "after/OFL.txt".`

### Results
 * browse report: [**Italic**](http://localhost:3000/browse/persistence/e4e4c63ae9cf7da02eac9d81b07dd328193ccb6fe67c2dcfc245dcfc45f9d2cb:0/) or download: [zip file](http://localhost:3000/download/persistence/e4e4c63ae9cf7da02eac9d81b07dd328193ccb6fe67c2dcfc245dcfc45f9d2cb:0/Browser%20Diffs_ABeeZee_Italic.zip)
 * browse report: [**Regular**](http://localhost:3000/browse/persistence/a77c87272328d8c6d3bd422ffa95e1d78f62dabd419c4d472b23fa3200cbdc76:0/) or download: [zip file](http://localhost:3000/download/persistence/a77c87272328d8c6d3bd422ffa95e1d78f62dabd419c4d472b23fa3200cbdc76:0/Browser%20Diffs_ABeeZee_Regular.zip)

*started* Mon Oct 14 2019 20:29:09 GMT+0000 (Coordinated Universal Time)<br />
*finished* Mon Oct 14 2019 20:31:34 GMT+0000 (Coordinated Universal Time)

**Comment by graphicore** [comment]
Ouch, interesting. I'm sending the updated report comment to the wrong PR …

**Comment by graphicore** [comment]
Updated:

---
[full report](http://localhost:3000/dispatcher/process/6452559f-7960-4aeb-87b1-cc5b3a4000b9)

# Step # 0 Review the Request and Generate the Files Package

**finished: OK**

All tasks completed successfully.

### Task ApproveProcess OK

**@graphicore** confirms the family package.

Report…

## Files Package for *ABeeZee*
### Files
 * `ABeeZee-Italic.ttf` *47764 Bytes*
 * `ABeeZee-Regular.ttf` *46124 Bytes*
 * `DESCRIPTION.en_us.html` *345 Bytes*
 * `FONTLOG.txt` *1765 Bytes*
 * `METADATA.pb` *626 Bytes*
 * `OFL.txt` *4466 Bytes*


[zip file download](http://localhost:3000/download/persistence/a51770aeaf3d57a835da37f38b1dde3313ad4b6d747e49255385785782f2810e:8/ABeeZee.zip)


### Metadata
**commit** 1de10e9a33fbe586897d35f9da29ab95df1b6d37  
**commitDate** 2015-06-15T19:55:05.000Z  
**sourceDetails** 

&emsp;**status** `"OK"`  
&emsp;**name** `"ABeeZee"`  
&emsp;**keySuffix** `""`  
&emsp;**nameConfirmed** `"Passed"`  
&emsp;**upstream** `"https://github.com/googlefonts/abeezee.git"`  
&emsp;**branch** `""`  
&emsp;**fontfilesPrefix** `"fonts/ttf/ABeeZee-"`  
&emsp;**genre** `"Sans Serif"`  
&emsp;**designer** `""`  
**familyPath** fonts/ttf  
**repository** https://github.com/googlefonts/abeezee.git  
**branch** master  
**googleMasterDir** ofl/abeezee  
**isUpdate** `true`  
**licenseDir** ofl


---

# Step # 1 Quality Assurance

**finished: OK**

All tasks completed successfully.

### Task Fontbakery OK

**@graphicore** Font Bakery looks good.

Report…

## [Font Bakery Result](http://localhost:3000/report/b1325fd6-8276-4a40-9e33-410f59caabf2)

| 💔 ERROR | 🔥 FAIL | ⚠ WARN | 💤 SKIP | 🛈 INFO | 🍞 PASS |
|:-----:|:----:|:----:|:----:|:----:|:----:|
| 0 | 14 | 10 | 57 | 11 | 200 |
| 0 % | 4.79 % | 3.42 % | 19.52 % | 3.77 % | 68.49 % |

*created* Mon Oct 14 2019 16:00:47 GMT+0000 (Coordinated Universal Time)<br />
*started* Mon Oct 14 2019 16:00:48 GMT+0000 (Coordinated Universal Time)<br />
*finished* Mon Oct 14 2019 16:02:53 GMT+0000 (Coordinated Universal Time)

### Task Diffenator OK

**@graphicore** Diffenator is looking  good.

### Task BrowsersDiffsAndPreviews OK

**@graphicore** Browsers diffs and previews are looking  good.

**Comment by graphicore** [comment]
Updated:

---
[full report](http://localhost:3000/dispatcher/process/5a9bc214-7b36-4f90-956c-a4125d43bc8f)

# Step # 0 Review the Request and Generate the Files Package

**finished: OK**

All tasks completed successfully.

### Task ApproveProcess OK

**@graphicore** confirms the family package.

Report…

## Files Package for *ABeeZee*
### Files
 * `ABeeZee-Italic.ttf` *47764 Bytes*
 * `ABeeZee-Regular.ttf` *46124 Bytes*
 * `DESCRIPTION.en_us.html` *345 Bytes*
 * `FONTLOG.txt` *1765 Bytes*
 * `METADATA.pb` *626 Bytes*
 * `OFL.txt` *4466 Bytes*


[zip file download](http://localhost:3000/download/persistence/a51770aeaf3d57a835da37f38b1dde3313ad4b6d747e49255385785782f2810e:9/ABeeZee.zip)


### Metadata
**commit** 1de10e9a33fbe586897d35f9da29ab95df1b6d37  
**commitDate** 2015-06-15T19:55:05.000Z  
**sourceDetails** 

&emsp;**status** `"OK"`  
&emsp;**name** `"ABeeZee"`  
&emsp;**keySuffix** `""`  
&emsp;**nameConfirmed** `"Passed"`  
&emsp;**upstream** `"https://github.com/googlefonts/abeezee.git"`  
&emsp;**branch** `""`  
&emsp;**fontfilesPrefix** `"fonts/ttf/ABeeZee-"`  
&emsp;**genre** `"Sans Serif"`  
&emsp;**designer** `""`  
**familyPath** fonts/ttf  
**repository** https://github.com/googlefonts/abeezee.git  
**branch** master  
**googleMasterDir** ofl/abeezee  
**isUpdate** `true`  
**licenseDir** ofl


---

# Step # 1 Quality Assurance

**finished: OK**

All tasks completed successfully.

### Task Fontbakery OK

**@graphicore** Font Bakery looks good.

Report…

## [Font Bakery Result](http://localhost:3000/report/b1325fd6-8276-4a40-9e33-410f59caabf2)

| 💔 ERROR | 🔥 FAIL | ⚠ WARN | 💤 SKIP | 🛈 INFO | 🍞 PASS |
|:-----:|:----:|:----:|:----:|:----:|:----:|
| 0 | 14 | 10 | 57 | 11 | 200 |
| 0 % | 4.79 % | 3.42 % | 19.52 % | 3.77 % | 68.49 % |

*created* Mon Oct 14 2019 16:00:47 GMT+0000 (Coordinated Universal Time)<br />
*started* Mon Oct 14 2019 16:00:48 GMT+0000 (Coordinated Universal Time)<br />
*finished* Mon Oct 14 2019 16:02:53 GMT+0000 (Coordinated Universal Time)

### Task Diffenator OK

**@graphicore** Diffenator is looking  good.

### Task BrowsersDiffsAndPreviews OK

**@graphicore** Browsers diffs and previews are looking  good.

**Comment by vv-monsalve** [comment]
> Ouch, interesting. I'm sending the updated report comment to the wrong PR …

Yes indeed, there are three now about ABeeZee Font on Bebas PR, is it a bug?

**Comment by graphicore** [comment]
fixed already :-)

**Comment by vv-monsalve** [comment]
Great :)

**Pull request closed without merging**
